default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  allow_concurrency: true
development:
  <<: *default
  database: anifag_com_dev
  username: dev
  password: '321321'
  min_messages: warning
test:
  <<: *default
  database: anifag_com_test
  username: dev
  password: '321321'
  min_messages: error
production:
  <<: *default
  database: anifag_com
  username: dev
  password: '321321'
  min_messages: error
