toolbar:
  - code | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect | cut copy paste | bullist numlist | outdent indent | blockquote | undo redo | removeformat subscript superscript
  - preview | image media | link
plugins:
  - code
  - preview
  - media
  - image
  - link
