version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    env_file:
      - ./env/infra/postgres.env
    volumes:
      - ./tmp/infra/data/postgres:/var/lib/postgresql/data/pgdata